spring.application.name=garage

server.port=8083

spring.datasource.url=jdbc:mariadb://172.23.32.1:3306/garagedb
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

services.bikes.url=http://bike:8081
services.cars.url=http://cars:8082

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
